### ISSUE TITLE
Invalid non-string/buffer chunk

### ISSUE THREAD

**Issue by kamwing** [loulin/skipper-qiniu#1]
`> skipper-qiniu@0.1.1 test /Users/kamwing/Desktop/skipper-qiniu

> node -e "require('skipper-adapter-tests')({mocha: { timeout: 360000 }, module: require('./'), bucket:process.env.BUCKET || 'skipper-adapter-tests', accessKey: process.env.ACCESSKEY, secretKey: process.env.SECRETKEY});"

  when some big files start coming in, this adapter
    1) should work properly with 2 simultaneous requests with decent-sized (1.5MB) files

  after uploading a file using this adapter, Skipper
    each file metadata object
      field
      file descriptor (`fd`)
      type

  under a bit of load, this adapter

  this adapter

  this adapter's impact on `req.body` ::

  Ignoring :: req.file("foo"), when a file upload is sent to the "bar" field ::

  req.file(...).pipe(...) ::

  req.file(...).upload(...) ::

  0 passing (375ms)
  1 failing

  1) when some big files start coming in, this adapter should work properly with 2 simultaneous requests with decent-sized (1.5MB) files:
     Uncaught TypeError: Invalid non-string/buffer chunk
      at chunkInvalid (_stream_readable.js:399:10)
      at readableAddChunk (_stream_readable.js:144:12)
      at Readable.push (_stream_readable.js:130:10)
      at Object.put (/Users/kamwing/Desktop/skipper-qiniu/node_modules/qiniu/qiniu/io.js:58:6)
      at Writable.onFile (/Users/kamwing/Desktop/skipper-qiniu/index.js:65:16)
      at doWrite (_stream_writable.js:307:12)
      at writeOrBuffer (_stream_writable.js:293:5)
      at Writable.write (_stream_writable.js:220:11)
      at Transform.ondata (_stream_readable.js:555:20)
      at emitOne (events.js:96:13)`

请问下这个问题可能是什么原因导致的吗？

**Comment by loulin** [comment]
抱歉，使用这个skipper还需要修改qiniu的内容，因为已经放弃sails了，所以没有打算去更新qiniu。
